name: Build PDFReader APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: List Release APK Directory Contents
      run: |
        echo "Listing contents of app/build/outputs/apk/release/:"
        ls -R app/build/outputs/apk/release/ || true # Use || true to prevent failure if directory is empty
        echo "Listing contents of app/build/outputs/apk/:"
        ls -R app/build/outputs/apk/ || true
        echo "Listing contents of app/build/outputs/:"
        ls -R app/build/outputs/ || true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-apk
        path: app/build/outputs/apk/release/app-release.apk
