name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython "kivy[base]" "pymupdf" "pyjnius"

    # --- NEW STEP TO INSTALL ANDROID BUILD-TOOLS EXPLICITLY ---
    - name: Install Android Build Tools
      run: |
        # Buildozer downloads SDK to ~/.buildozer/android/platform/android-sdk
        # We need to explicitly install build-tools using sdkmanager
        # Use the latest command-line tools sdkmanager
        SDK_ROOT="${HOME}/.buildozer/android/platform/android-sdk"
        mkdir -p "${SDK_ROOT}/cmdline-tools/latest/bin"

        # Download and extract the latest cmdline-tools if not already there
        # This is often done by buildozer, but sometimes manual intervention helps.
        # Ensure sdkmanager is available.
        if [ ! -f "${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" ]; then
          echo "Downloading Android command-line tools..."
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8583075_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d "${SDK_ROOT}/cmdline-tools/latest"
          rm /tmp/cmdline-tools.zip
        fi

        # Make sure sdkmanager is executable
        chmod +x "${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"

        # List licenses and accept them (crucial for some tools like aidl)
        # This is often the root cause of 'aidl not found' - the license wasn't accepted.
        echo "Accepting Android SDK licenses..."
        yes | "${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${SDK_ROOT}" --licenses

        # Install build-tools for API 30
        echo "Installing Android build-tools;30.0.3..."
        "${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${SDK_ROOT}" "build-tools;30.0.3"

    - name: Build Android Debug APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk
