name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # --- Use the dedicated Android SDK Setup Action with precise versions ---
    - name: Set up Android SDK and accept licenses
      uses: android-actions/setup-android@v3
      with:
        # Match your buildozer.spec's android.api
        api-level: 30
        # Explicitly install build-tools 30.0.3, which is stable for API 30
        build-tools: 30.0.3
        # Ensure platform-tools are installed (adb, etc.)
        components: 'platform-tools'
        # The 'setup-android' action generally handles license acceptance automatically
        # when you specify api-level and build-tools. No separate --licenses step needed.

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython "kivy[base]" "pymupdf" "pyjnius"

    - name: Build Android Debug APK
      run: |
        # Ensure Buildozer knows where the SDK is that was set up by the action
        # The 'setup-android' action usually sets ANDROID_HOME and PATH automatically.
        # This step just executes the Buildozer command.
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk
