name: Build PDFReader App

on:
  push:
    branches:
      - main # Or your main development branch
  workflow_dispatch: # Allows manual triggering from GitHub UI
    inputs:
      reason:
        description: 'Reason for running the workflow manually'
        required: false
        default: 'Manual trigger from GitHub UI'

jobs:
  build_linux: # Job to build for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Using Python 3.9 for broad compatibility

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyQt5 and PyMuPDF (fitz)
        pip install pyinstaller PyQt5 PyMuPDF

    - name: Create Linux executable
      run: |
        # Use the correct script name: PDFReader.py
        pyinstaller --onefile --windowed --name "PDFReader" PDFReader.py

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Linux
        path: dist/PDFReader # The path where PyInstaller puts the executable
