name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        # Add Cython here, as it's a core build dependency for Buildozer/Python-for-Android
        pip install buildozer Cython "kivy[base]" "pymupdf" "pyjnius"
        # The exact Cython version might sometimes matter, but usually latest works.
        # If you encounter issues later, try pinning it: pip install Cython==0.29.33 (a commonly stable version)

    - name: Build Android Debug APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk
