name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Or 'zulu', 'adopt', etc.
        java-version: '17' # Java 17 is generally recommended for recent Android SDK/NDK

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Kivy/Buildozer often work well with 3.9

    - name: Install Buildozer and Kivy (for dependencies)
      run: |
        python -m pip install --upgrade pip
        pip install buildozer "kivy[base]" "pymupdf" "pyjnius"

    - name: Configure Buildozer
      run: |
        # Buildozer needs to be initialized. This generates the buildozer.spec
        # If buildozer.spec already exists (which it should, from your repo),
        # this command will simply ensure basic setup.
        # It also downloads SDK/NDK the first time.
        buildozer init
        # Modify buildozer.spec if needed directly from script (unnecessary if you pre-configured)
        # sed -i 's/^#android.api = 27/android.api = 30/' buildozer.spec
        # etc. (but we assume you've set it correctly above)

    - name: Build Android Debug APK
      run: |
        # This command triggers the full Android build process
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk # Buildozer places APKs in the 'bin' directory
