name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # --- NEW STEP: Use the dedicated Android SDK Setup Action ---
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3 # Use the official action
      with:
        api-level: 30 # Match your buildozer.spec's android.api
        build-tools: 30.0.3 # Explicitly install a common working build-tools version
        # You can add other components like platform-tools if needed:
        # components: 'platform-tools' 
        # auto-license-accept: true is often default or handled by api-level/build-tools

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython "kivy[base]" "pymupdf" "pyjnius"

    - name: Build Android Debug APK
      run: |
        # Buildozer will now find the SDK tools set up by the 'setup-android' action
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk
