name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        # Install buildozer first, then other requirements that buildozer will bundle
        pip install buildozer "kivy[base]" "pymupdf" "pyjnius"

    - name: Build Android Debug APK
      run: |
        # Buildozer will automatically find and use the existing buildozer.spec file.
        # This command triggers the full Android build process.
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk # Buildozer places APKs in the 'bin' directory
