name: Build Android PDFReader APK

on:
  workflow_dispatch: # Allows manual triggering only

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Use the dedicated Android SDK Setup Action for core SDK
    - name: Set up Android SDK (core components)
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        components: 'platform-tools'

    # Install Autotools dependencies (keep this, it's necessary)
    - name: Install Autotools for C/C++ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool build-essential pkg-config

    - name: Install Buildozer and Kivy dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure buildozer is latest, and its underlying python-for-android is updated
        pip install "buildozer[full]" Cython "kivy[base]" "pymupdf" "pyjnius"

    # --- NEW STEP: Clean Buildozer Cache ---
    - name: Clean Buildozer cache
      run: |
        # This removes all cached SDKs, NDKs, and build artifacts,
        # forcing a fresh download and setup. Crucial for persistent issues.
        buildozer android clean

    - name: Build Android Debug APK
      run: |
        # Buildozer will now perform a fresh build
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFReader-Android-APK
        path: bin/*.apk
